x = input('Digite algo.. ')
print(type(x))
print('é alfanumérico?? -', x.isalnum())
print('é alfabético? -',x.isalpha())
print('é ascii? -',x.isascii())
print('está em caixa baixa? -',x.islower())
print('é um numero? -',x.isnumeric())
print('é imprimivel? -',x.isprintable())
print('é um espaço? -',x.isspace())
print('é um titulo? -',x.istitle())
print('está em caixa alta? -',x.isupper())